### ISSUE TITLE
Lots of department maintenence door's access is broken

### ISSUE THREAD

**Issue by Muncher2112** [butmun/InterHippie#82]
**Describe the bug**
People with maint access can walk into lots of departments

**To Reproduce**
Walk into security as engineer from maintenance

**Expected behavior**
Department maint doors have correct access

**Comment by Muncher2112** [comment]
Arbiter maint, can access locker and potentially interrogation room


![](https://i.gyazo.com/0194a5d4b2ffa3c67cb69c7387582f9e.png)

Viro maint 


![](https://i.gyazo.com/32dbea2196db6bae933dd9b5286eeac4.png)

Botany in general seems to be open to the public


![](https://i.gyazo.com/41b738351f6713d859d7cdf77a499c81.png)

**Comment by SireTurret** [comment]
@butmun

**Comment by SireTurret** [comment]
this was fixed but no one told me
